In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

from sklearn.datasets import load_diabetes

In [2]:
df = load_diabetes()


In [3]:
df

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [4]:
X=df.data  #input columns 
Y = df.target

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=45)

In [6]:
X_train

array([[-0.08906294, -0.04464164, -0.01159501, ...,  0.03430886,
         0.02268774, -0.00936191],
       [-0.03457486, -0.04464164, -0.0374625 , ..., -0.00259226,
        -0.03074792, -0.07149352],
       [ 0.01628068,  0.05068012, -0.04500719, ..., -0.03949338,
        -0.03074792,  0.03620126],
       ...,
       [ 0.01628068, -0.04464164,  0.02612841, ..., -0.03395821,
        -0.05140387, -0.02593034],
       [-0.09632802, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.04688253, -0.07977773],
       [ 0.08166637,  0.05068012,  0.00672779, ...,  0.09187461,
         0.05471997,  0.00720652]])

In [7]:
y_train

array([206., 128., 102.,  88., 346., 268., 198.,  96.,  78.,  87., 170.,
       292., 161., 118., 202.,  53., 103., 129.,  95., 179.,  89.,  68.,
       151., 275.,  90., 281., 150., 111., 116.,  66., 208., 173., 262.,
       110.,  94., 113.,  83., 190.,  96., 303.,  73., 293., 275., 197.,
       221., 237.,  50., 142., 200., 151., 109.,  70., 152., 261., 308.,
       195., 129., 214., 122.,  95., 259.,  63., 104., 143.,  78., 317.,
       281., 173.,  93., 272., 129.,  77.,  75.,  87., 139., 310., 233.,
        88., 263.,  59., 265., 199., 236., 103., 179., 210., 168., 123.,
       128.,  47., 277.,  60.,  85., 237., 192., 230., 225., 235., 241.,
        55., 295., 257.,  71., 110., 189., 151.,  58.,  97., 229., 120.,
       280., 332.,  49., 201.,  54., 288., 259., 146., 154., 336., 166.,
       258., 219.,  97., 124., 296., 275., 279.,  81., 170.,  52., 197.,
       297., 121., 178., 170., 109.,  77.,  65.,  71.,  47., 111., 100.,
        91.,  94., 104., 150., 152.,  44., 104.,  8

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression() 
model.fit(X_train,y_train)  #finding the best fit line

LinearRegression()

In [9]:
model.intercept_   # intercept 

152.13623331746496

In [10]:
model.coef_  #slope 

array([  23.45465406, -247.42747406,  492.1087518 ,  329.35876431,
       -970.79723039,  573.54295519,  182.42162368,  255.92168168,
        794.21609282,   89.32249214])

In [11]:
y_hat = model.predict(X_test) #predicting the X_train values 

In [12]:
from sklearn.metrics import r2_score
r2_score(y_test,y_hat)

0.5188113124539246

In [13]:
## Reguralisation 

from sklearn.linear_model import Ridge
rg = Ridge(alpha=0.1)

In [14]:
rg.fit(X_train,y_train)

Ridge(alpha=0.1)

In [15]:
y_hat_rg = rg.predict(X_test)

In [16]:
rg.intercept_

152.0714129017282

In [17]:
rg.coef_

array([  31.03389163, -204.8305909 ,  464.8963454 ,  304.96414918,
        -95.76037039,  -87.52969228, -183.81809293,  147.49794012,
        425.85392451,  110.21559915])

In [18]:
r2_score(y_test,y_hat_rg)

0.5208421054129914